server:
  publicHost: localhost
  publicPort: 8080
  publicScheme: http
  privateHost: localhost
  privatePort: 8081
  privateScheme: http

database:
  host: localhost
  port: 5432
  name: code_butler
  username: postgres
  password: password

logging:
  logAllQueries: true
  logSlowQueries: true
  logLevel: info

